FROM continuumio/miniconda3:4.9.2-alpine

WORKDIR /opt/app

COPY . ./

RUN conda env create -f environment.yml && \
    conda clean --all --yes

SHELL ["conda", "run", "-n", "SAMPL-hello-world", "/bin/ash", "-c"]

RUN pip install .

RUN conda install -n SAMPL-hello-world Click

RUN dependencies/mgl/install.sh -c 1

ENV PATH="/opt/app/dependencies/mgl/:$PATH"


ENTRYPOINT ["conda", "run", "-n", "SAMPL-hello-world", "dock"]

