web: gunicorn --bind :8000 --workers 3 --threads 2 sampl.wsgi:application
scheduler: dask-scheduler --host 127.0.0.1:8786
worker: DJANGO_SETTINGS_MODULE=sampl.settings_prod dask-worker --preload daskworkerinit.py 127.0.0.1:8786
jupyterlab: DJANGO_SETTINGS_MODULE=sampl.settings_prod jupyter-lab --no-browser --port 8989 --ip localhost --ServerApp.token=''
