[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sampl.settings_dev"
addopts = "-vv"

[tool.pylint.format]
# Note: .pylintrc file overrides pylint settings in this file
max-line-length = "88"

[tool.pylint.messages_control]
disable = "missing-class-docstring, missing-function-docstring"

[tool.isort]
profile = "black"
skip = "core/migrations/"

[tool.black]
exclude = "core/migrations/"
