[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sampl.settings_dev"
addopts = "-vv"

[tool.pylint.messages_control]
disable = "R, C, E, W1618, W0511"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
ignore = "conftest.py"
ignore-paths = ["^app/tests/.*$",
               "^app/referee/tests/.*$"]

[tool.isort]
profile = "black"
skip = "core/migrations/"

[tool.black]
exclude = "core/migrations/"
