# Generated by Django 3.1.7 on 2021-04-08 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMaker',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.challenge')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.container')),
            ],
            options={
                'get_latest_by': ('created_at',),
                'abstract': False,
            },
        ),
    ]
