# Generated by Django 3.2.4 on 2021-06-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210604_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretype',
            name='level',
            field=models.CharField(choices=[('evaluation', 'Evaluation'), ('submission_run', 'Submission Run')], default='evaluation', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='scoretype',
            unique_together={('challenge', 'key', 'level')},
        ),
    ]
