# Generated by Django 3.2.4 on 2021-06-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210612_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to='file_uploads/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
