# Generated by Django 3.2.4 on 2021-06-29 19:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_filevalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlobValue',
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='value',
            field=models.FileField(upload_to=core.models._upload_location),
        ),
    ]
