# Generated by Django 3.2.4 on 2021-06-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210629_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevalue',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filevalue',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
        migrations.AddField(
            model_name='textvalue',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textvalue',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
    ]
