# Generated by Django 3.2 on 2021-08-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210629_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the object in the table for that type of value (Float Value, Text Value, File Value)'),
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
        migrations.AlterField(
            model_name='floatvalue',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
        migrations.AlterField(
            model_name='inputvalue',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the object in the table for that type of value (Float Value, Text Value, File Value)'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the object in the table for that type of value (Float Value, Text Value, File Value)'),
        ),
        migrations.AlterField(
            model_name='textvalue',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluation'),
        ),
    ]
