# Generated by Django 3.2.6 on 2021-09-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210831_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='execution_options_json',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='sample_data_url',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='sample_score_reference_url',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='secret_data_url',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='secret_score_reference_url',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
