# Generated by Django 3.2.7 on 2021-09-27 14:49

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210915_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(db_index=False)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=core.models._container_file_location)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='core.container')),
            ],
            options={
                'unique_together': {('container', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='SubmissionArg',
        ),
    ]
