# Generated by Django 3.2.7 on 2021-10-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210927_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionrun',
            options={},
        ),
        migrations.AddField(
            model_name='submissionrun',
            name='log_stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionrun',
            name='log_stdout',
            field=models.TextField(blank=True),
        ),
    ]
