# Generated by Django 3.2.8 on 2021-10-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210927_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, help_text='help text for notes field', null=True),
        ),
    ]
