# Generated by Django 3.2.7 on 2021-10-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_submission_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='draft_mode',
            field=models.BooleanField(default=False, help_text='Use draft mode if you would like to test your container/submission before formal submission. In draft mode, fields below may be left incomplete. Once you are happy with your submission, you must uncheck draft mode before finalizing your submission.'),
        ),
    ]
