# Generated by Django 3.2.9 on 2021-11-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_submission_draft_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionrun',
            options={},
        ),
        migrations.AddField(
            model_name='submissionrun',
            name='log_stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submissionrun',
            name='log_stdout',
            field=models.TextField(blank=True),
        ),
    ]
