# Generated by Django 3.2.9 on 2021-11-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211109_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'Failure'), ('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('CANCEL_PENDING', 'Cancel Pending')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='submissionrun',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'Failure'), ('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('CANCEL_PENDING', 'Cancel Pending')], max_length=25),
        ),
    ]
