# Generated by Django 4.0.3 on 2022-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211125_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.CharField(choices=[('docker', 'Docker'), ('singularity_local', 'Singularity Local')], help_text='State the type of container image you are submitting `Docker` or `Singularity`.', max_length=255, null=True),
        ),
    ]
