# Generated by Django 4.0.4 on 2022-05-17 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_container_container_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="max_batch_size",
            field=models.PositiveIntegerField(
                default=0, help_text="0 to disable batching"
            ),
        ),
        migrations.AddField(
            model_name="inputelement",
            name="is_parent",
            field=models.BooleanField(
                default=False,
                help_text="Parent elements won't be evaluated. They are used to group common values",
            ),
        ),
        migrations.AddField(
            model_name="inputelement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Inherit common values from parent element, eg. protein PDB file",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.inputelement",
            ),
        ),
        migrations.AddField(
            model_name="valuetype",
            name="on_parent_flag",
            field=models.BooleanField(
                choices=[(True, "On parent"), (False, "On child")],
                default=False,
                help_text="For input elements, should this value be set on the parent or on the child? e.g. protein PDB structure should only be set on the parent; ligand SMILES should only be set on the child",
            ),
        ),
        migrations.CreateModel(
            name="InputBatchGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.challenge"
                    ),
                ),
            ],
            options={
                "get_latest_by": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InputBatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "batch_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.inputbatchgroup",
                    ),
                ),
            ],
            options={
                "get_latest_by": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InputBatchMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.inputbatch",
                    ),
                ),
                (
                    "batch_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.inputbatchgroup",
                    ),
                ),
                (
                    "input_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.inputelement",
                    ),
                ),
            ],
            options={
                "unique_together": {("batch_group", "input_element")},
            },
        ),
    ]
