# Generated by Django 4.0.5 on 2022-06-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_challenge_max_batch_size_inputelement_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textvalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
    ]
