# Generated by Django 4.0.5 on 2022-06-21 21:30

import core.models.batch_related
import core.models.run_related
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_evaluation_status_alter_submissionrun_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='challenge',
            name='max_batch_size',
            field=models.PositiveIntegerField(default=0, help_text='0 to disable batching'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='submission_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.submissionrun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filevalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputelement',
            name='is_parent',
            field=models.BooleanField(default=False, help_text="Parent elements won't be evaluated. They are used to group common values"),
        ),
        migrations.AddField(
            model_name='inputelement',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Inherit common values from parent element, eg. protein PDB file', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='submission_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.submissionrun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textvalue',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuetype',
            name='batch_method',
            field=models.CharField(blank=True, choices=[('', 'None'), ('csv', 'CSV'), ('mol', 'MOL or SDF')], default='csv', max_length=10),
        ),
        migrations.AddField(
            model_name='valuetype',
            name='on_parent_flag',
            field=models.BooleanField(choices=[(True, 'On parent'), (False, 'On child')], default=False, help_text='For input elements, should this value be set on the parent or on the child? e.g. protein PDB structure should only be set on the parent; ligand SMILES should only be set on the child'),
        ),
        migrations.AlterField(
            model_name='submissionrunscore',
            name='submission_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submissionrun'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('submission_run', 'input_element', 'score_type')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('submission_run', 'input_element', 'value_type')},
        ),
        migrations.CreateModel(
            name='InputBatchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_batch_size', models.PositiveIntegerField(help_text='Value of setting when batch group was created')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.challenge')),
            ],
            options={
                'get_latest_by': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatchgroup')),
                ('parent_input_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement')),
            ],
            options={
                'get_latest_by': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to=core.models.batch_related.batch_upload_location)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatch')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.valuetype')),
            ],
            options={
                'get_latest_by': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_stdout', models.TextField(blank=True)),
                ('log_stderr', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FAILURE', 'Failure'), ('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('PENDING_REMOTE', 'Pending Remote'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('CANCEL_PENDING', 'Cancel Pending')], default='PENDING', max_length=25)),
                ('input_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatch')),
                ('submission_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submissionrun')),
            ],
            options={
                'unique_together': {('submission_run', 'input_batch')},
            },
            bases=(models.Model, core.models.run_related.StatusMixin),
        ),
        migrations.RemoveField(
            model_name='evaluationscore',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='filevalue',
            name='batch_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batchevaluation'),
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='batch_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batchevaluation'),
        ),
        migrations.AddField(
            model_name='textvalue',
            name='batch_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.batchevaluation'),
        ),
        migrations.CreateModel(
            name='InputBatchMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatch')),
                ('batch_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatchgroup')),
                ('input_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputelement')),
            ],
            options={
                'unique_together': {('batch_group', 'input_element')},
            },
        ),
    ]
