# Generated by Django 4.0.5 on 2022-06-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_evaluationscore_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuetype',
            name='batch_method',
            field=models.CharField(blank=True, choices=[('', 'None'), ('csv', 'CSV'), ('sdf', 'MOL or SDF')], default='csv', max_length=10),
        ),
    ]
