# Generated by Django 4.0.5 on 2022-06-16 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_inputbatch_parent_input_element'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='input_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.inputelement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='submission_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.submissionrun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='submission_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.submissionrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissionrunscore',
            name='submission_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submissionrun'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('submission_run', 'input_element', 'score_type')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('submission_run', 'input_element', 'value_type')},
        ),
        migrations.DeleteModel(
            name='BatchPrediction',
        ),
        migrations.RemoveField(
            model_name='evaluationscore',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='evaluation',
        ),
    ]
