# Generated by Django 4.0.6 on 2022-08-17 14:58

import core.models.values
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_batchevaluationfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchfile',
            options={},
        ),
        migrations.CreateModel(
            name='AnswerKeyBatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to=core.models.answer_key_batch_upload_location)),
                ('input_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inputbatch')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.valuetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
